referenceDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.9999
      keepDensities: 1
      keepNormals: 0
      
  - MaxDensityDataPointsFilter:
      maxDensity: 40

  - BoundingBoxDataPointsFilter:
      xMin: -1.0
      xMax: 5.0
      yMin: -0.8
      yMax: 0.8
      zMin: -0.5
      zMax: 1.8
      removeInside: 1

readingDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.9999
      keepDensities: 1
      keepNormals: 0
      
  - MaxDensityDataPointsFilter:
      maxDensity: 40

  - BoundingBoxDataPointsFilter:
      xMin: -5.0
      xMax: 1.0
      yMin: -0.8
      yMax: 0.8
      zMin: -0.5
      zMax: 1.8
      removeInside: 1

matcher:
  KDTreeMatcher:
    maxDist: 6.0
    knn: 3
    epsilon: 0.0

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.8

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.0000001
      minDiffTransErr: 0.000001
      smoothLength: 5
  - CounterTransformationChecker:
      maxIterationCount: 100
  - BoundTransformationChecker:
      maxRotationNorm: 0.90
      maxTranslationNorm: 4.00

inspector:
  NullInspector

logger:
  FileLogger
